artifact_uri: file:///Users/georgeboorman/Documents/udacity/cd0581-building-a-reproducible-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/mlruns/0/7d4c2cdaac9649c3b0a5cbadb66dd244/artifacts
end_time: 1664026344444
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 7d4c2cdaac9649c3b0a5cbadb66dd244
run_uuid: 7d4c2cdaac9649c3b0a5cbadb66dd244
source_name: ''
source_type: 4
source_version: ''
start_time: 1664026311469
status: 4
tags: []
user_id: georgeboorman
