artifact_uri: file:///Users/georgeboorman/Documents/udacity/cd0581-building-a-reproducible-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/mlruns/0/3202392c47784a648189823722ec7690/artifacts
end_time: 1664026344328
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3202392c47784a648189823722ec7690
run_uuid: 3202392c47784a648189823722ec7690
source_name: ''
source_type: 4
source_version: ''
start_time: 1664026312718
status: 4
tags: []
user_id: georgeboorman
